BreakingNews.UI/ViewModels/AccountViewModel.cs
namespace BreakingNews.UI.ViewModels
{
    public class AccountViewModel
    {
        public string DisplayName { get; set; }
    }
}

BreakingNews.UI/ViewModels/MenuItemViewModel.cs
using System.Collections.Generic;

namespace BreakingNews.UI.ViewModels
{
    public class MenuItemViewModel
    {
        public string Name { get; set; }
        public string ActionName { get; set; } = "Index";
        public string ControllerName { get; set; }
        public string IconCssClass { get; set; }
        public bool IsHome { get; set; }
        public IDictionary<string, string> Parameters { get; set; }
    }
}

BreakingNews.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BreakingNews.UI.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
    }
}

BreakingNews.UI/Controllers/MediaController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace BreakingNews.UI.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MediaController : ControllerBase
    {
        readonly IHostingEnvironment _env;

        public MediaController(IHostingEnvironment env)
        {
            _env = env;
        }

        [Route("[action]/{name}")]
        public IActionResult Test(string name)
        {
            return new JsonResult(new { name });
        }

        [Route("[action]")]
        [HttpPost]
        public async Task<IActionResult> Upload()
        {
            IFormFileCollection files = Request.Form.Files;
            var result = new List<string>();
            foreach (var file in files)
            {
                string path = "/files/" + file.FileName;
                using (var fs = new FileStream(_env.WebRootPath + path, FileMode.Create))
                {
                    await file.CopyToAsync(fs);
                }
                result.Add(path);
            }
            return new JsonResult(result);
        }
    }
}

BreakingNews.UI/ViewComponents/AccountViewComponent.cs
using BreakingNews.Application.Interfaces;
using BreakingNews.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BreakingNews.UI.ViewComponents
{
    public class AccountViewComponent : ViewComponent
    {
        private readonly IUserManager _userManager;

        public AccountViewComponent(IUserManager userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync();
            var viewModel = new AccountViewModel
            {
                DisplayName = $"{user.FirstName} {user.LastName}"
            };
            return View(viewModel);
        }
    }
}

BreakingNews.UI/ViewComponents/MenuViewComponent.cs
using BreakingNews.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;

namespace BreakingNews.UI.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IConfiguration _configuration;

        public MenuViewComponent(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IViewComponentResult Invoke()
        {
            var items = _configuration.GetSection("MenuItems")
                .Get<IEnumerable<MenuItemViewModel>>();
            return View(items);
        }
    }
}

BreakingNews.UI/ViewComponents/NoticeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace BreakingNews.UI.ViewComponents
{
    public class NoticeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
            => View();
    }
}

BreakingNews.UI/ViewComponents/SearchViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace BreakingNews.UI.ViewComponents
{
    public class SearchViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
            => View();
    }
}

BreakingNews.UI/ViewComponents/TouchViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace BreakingNews.UI.ViewComponents
{
    public class TouchViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
            => View();
    }
}

BreakingNews.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="page main-page">
    <div class="content content-30">
        <vc:touch />
    </div>
    <div class="content content-70"></div>
</div>

BreakingNews.UI/Views/Shared/Components/Account/Default.cshtml
@model AccountViewModel

<div class="account">
    <div class="account__image"></div>
    <div class="account__name">
        <span class="account__name-accent">@Model.DisplayName?[0]</span>
        <span class="account__name-other">@Model.DisplayName?.Substring(1, Model.DisplayName.Length - 1)</span>
    </div>
</div>

BreakingNews.UI/Views/Shared/Components/Menu/Default.cshtml
@model IEnumerable<MenuItemViewModel>

<nav class="navigation" role="navigation">
    <button class="navigation-button" aria-label="Navigation Menu" data-hamburger-button>
        <span class="navigation-button__icon"></span>
    </button>
    <ul class="navigation-list">
        @foreach (MenuItemViewModel item in Model)
        {
            <li class="navigation-list__item">
                <a class="navigation-link @(item.IsHome ? "home" : "")"
                   asp-controller="@item.ControllerName"
                   asp-action="@item.ActionName"
                   asp-all-route-data="@item.Parameters">
                    <span class="text">@item.Name</span>
                </a>
            </li>
        }
    </ul>
</nav>

BreakingNews.UI/Views/Shared/Components/Notice/Default.cshtml
<div id="noticeComponent" class="NoticeComponent"></div>

BreakingNews.UI/Views/Shared/Components/Search/Default.cshtml
<div id="searchComponent" class="SearchComponent" role="search"></div>

BreakingNews.UI/Views/Shared/Components/Touch/Default.cshtml
<div id="touchComponent" class="TouchesComponent"></div>

BreakingNews.UI/Views/Shared/_Favicon.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/static/media/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="~/static/media/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="~/static/media/favicon-16x16.png" />
<link rel="shortcut icon" type="image/x-icon" href="~/static/media/favicon.ico" />

<link rel="manifest" href="~/static/media/site.webmanifest" />
<link rel="mask-icon" sizes="any" href="~/static/media/favicon.svg" color="#116fff" />
<meta name="msapplication-TileColor" content="#116fff" />
<meta name="theme-color" content="#ffffff" />

BreakingNews.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <partial name="_Favicon" />
    <link rel="stylesheet" asp-href-include="~/static/css/vendor.css" asp-append-version="true" />
    <link rel="stylesheet" asp-href-include="~/static/css/common.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/static/css/main.css" asp-append-version="true" />

    <script asp-src-include="~/static/js/vendor.*.js" asp-append-version="true"></script>
    <script asp-src-include="~/static/js/common.*.js" asp-append-version="true"></script>
</head>
<body>
    <header class="site-header">
        <div class="container">
            <div class="container-wrapper">
                <div class="logo"></div>
                <vc:menu></vc:menu>
                <div class="to-right site-header__tools">
                    <vc:search></vc:search>
                    <vc:notice></vc:notice>
                    <vc:account></vc:account>
                </div>
            </div>
        </div>
    </header>
    <main class="container body-content">
        @RenderBody()
    </main>
    <script src="~/static/js/main.js" asp-append-version="true"></script>
</body>
</html>